services:
  web:
    build: 
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - EMAIL_USER=${EMAIL_USER}
        - EMAIL_PASS=${EMAIL_PASS}
    ports:
      - "3000:3000"     # 외부 80포트를 컨테이너 3000포트로 매핑
      - "3000:3000"   # EC2에서 로컬 nginx가 포워딩할 대상 포트
    env_file:
      - .env
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
