version: '3'
services:
  web:
    build: 
      context: .
      args:
        - MONGODB_URI=mongodb://seedwatercafe:seedwatercafe123!@184.73.144.148:27017/seedwatercafe?authSource=admin
    ports:
      - "80:3000"  # ✅ 수정된 부분
    environment:
      - MONGODB_URI=mongodb://seedwatercafe:seedwatercafe123!@184.73.144.148:27017/seedwatercafe?authSource=admin
      - NODE_ENV=production
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seedwatercafe
      - MONGO_INITDB_ROOT_PASSWORD=seedwatercafe123!
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 
