version: '3'
services:
  web:
    build: 
      context: .
      args:
        - MONGODB_URI=mongodb://seedwatercafe:seedwatercafe123!@184.73.144.148:27017/test?authSource=admin
    ports:
      - "80:3000"  # ✅ 수정된 부분
    environment:
      - MONGODB_URI=mongodb://seedwatercafe:seedwatercafe123!@184.73.144.148:27017/test?authSource=admin
      - NODE_ENV=production
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 
