// models/User.ts
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  MNO: { type: Number, required: true, unique: true },
  MON2: { type: Number, required: true },
  COMPANY: { type: String, default: null },
  NO: { type: Number, default: 1 },
  Name: { type: String, default: null },
  FIRST_NAME: { type: String, default: null },
  MIDDLE_NAME: { type: String, default: null },
  LAST_NAME: { type: String, default: null },
  Rate: { type: Number, default: null },
  RATE_CHANGE_DATE: { type: String, default: null },
  emp_id: { type: Number, default: null },
  NOTE: { type: String, default: null },
  WORKNOTE: { type: String, default: null },
  START: { type: String, default: null },
  END: { type: String, default: null },
  POSITION: { type: String, default: null },
  EMP_MASTER_CATE: { type: String, default: null },
  PAY_MASTER_CATE: { type: String, default: null },
  Status: { type: String, default: null },
  Tip_apply: { type: Number, default: null },
  labor_mastercol: { type: String, default: null },
  Performance_bonus: { type: Number, default: null },
  DateOfHire: { type: String, default: null },
  DateOfBirth: { type: String, default: null },
  sex: { type: Number, default: null },
  Address1: { type: String, default: null },
  Address2: { type: String, default: null },
  City: { type: String, default: null },
  State: { type: String, default: null },
  Zip: { type: String, default: null },
  Email: { type: String, default: null },
  PhoneNumber: { type: String, default: null },
  SSN: { type: String, default: null },
  Payperiod: { type: String, default: null },
  FMS: { type: Number, default: null },
  FMS_NO: { type: Number, default: null },
  SMS: { type: Number, default: null },
  SMS_NO: { type: Number, default: null },
  ame_reg: { type: String, default: null },
}, { timestamps: true });

export default mongoose.models.User || mongoose.model('User', UserSchema);
